#!/usr/bin/env bash
# Abort this process, If you set $ABORT_IF_EXIT_PID.
set -e
# Check to support tty.
if [ "$(tty>/dev/null;echo $?)" != "0" ];then
    DOCKERCOMPOSE_EXEC="docker-compose exec -T"
else
    DOCKERCOMPOSE_EXEC="docker-compose exec"
fi
# Visit https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers for info on how to fix this.
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf > /dev/null
sudo sysctl -p > /dev/null
if  [ "$(ls tmp/pids/server.pid 2>&1 > /dev/null; echo $?)" != "0" ];then
    echo -n "Wait to run dev server "
    while [ "$(ls tmp/pids/server.pid 2>&1 > /dev/null; echo $?)" != "0" ]
    do
        [ -v ABORT_IF_EXIT_PID ] && kill -0 $ABORT_IF_EXIT_PID >/dev/null 2>&1 || exit 1
        echo -n "."
        sleep 1
    done
    echo ""
fi
$DOCKERCOMPOSE_EXEC web /bin/bash -c ". /etc/profile.d/rvm.sh && . /root/.nvm/nvm.sh && RUBYOPT='-W:no-deprecated' bundle exec bin/rails $*"
