:toc: left
:sectlinks:
:toc-title: 目次

= Setting
[.env]ファイルの設定内容について.env-exampleを参考に説明します。

include::google_translate.adoc[]

=== 名前空間
redis, mongodb, sidekiqなどのNAMESPACEに使用されます。

 NAMESPACE=newsdict

=== 本番用FQDN
workerからtwitterに投稿される際に使われるFQDNです。

 PROD_FQDN=https://newsdict.jp

=== 開発用domain
pumaでローカルドメインを待ち受けるために使用されます。

 LOCAL_DOMAIN=newsdict.jp

=== Timezone
railsのtimezoneを設定します。

 TIMEZONE=Tokyo

=== Default Locale
アプリ言語コードを設定します。

 default_locale=ja

=== Maximum number of admin's members
管理画面を操作できる最大ユーザ数を設定します。 +
デフォルトテーマでは、最大ユーザ数に到達するとトップページに管理画面へのリンク[Setting]が出なくなります。

 MAX_MEMBER_COUNT=2
 
=== 送信元メールアドレス

=== super_admin email
管理者ユーザのメールアドレスを設定します。 +
このメールアドレスで登録するとすべての管理項目を編集できるようになります。

 ADMIN_USER_EMAIL=dummy@dummy.com

=== redis host and port
ワーカーにsidekiqを使用しており、storageにはredisを使用しています。

 REDIS_HOST=dummy.com
 SIDEKIQ_NAMESPACE=sidekiq

=== mongodb host
メインDBにmongodbを使用しているので適切なホスト名を設定してください。

 MONGODB_HOST=dummy.com

=== webpack-dev-server
開発環境で使用するwebpackerドメイン名を設定します。

 WEBPACK_DEV_SERVER_PUBLIC=1.2.3.4

=== Logging to STDOUT
開発環境でログを出力したくない場合は以下をコメントアウトしてください

 RAILS_LOG_TO_STDOUT=1

=== asciidoctor用のskin名
link:https://github.com/darshandsoni/asciidoctor-skins[asciidoctor-skins]のテーマ名を指定します。 +
これはdocumentで使用されるasciidoctorのテーマに使用されます。

 asciidoctor_theme=boot-darkly

link:/[目次へ戻る]